### ISSUE TITLE
Publish index.html as Github Pages

### ISSUE THREAD

**Issue by GregTonoski** [SpaceHodler/SeedXOR#1]
As a user, I would like to play with the tool on the https://spacehodler.github.io/SeedXOR before downloading the index.html so that I can evaluate if I really want it.

Hint: enable webpages in settings of the repo as described at the https://pages.github.com/.

**Comment by SpaceHodler** [comment]
Sorry for the late response, I wasn't watching the repo.
This is now done.

**Comment by GregTonoski** [comment]
Thanks. 

Can I ask you to add the link "https://spacehodler.github.io/SeedXOR/" to the About section, please: 
![image](https://github.com/SpaceHodler/SeedXOR/assets/111286121/42228685-1456-402b-b904-8a09e7129d05)?

**Comment by SpaceHodler** [comment]
Added the link
